# _config.yml

# Site settings
title: "Top Lane Factors to Win Analysis"
description: "An analysis of the critical factors leading to success in the top lane role in League of Legends esports."
url: "https://ryansen.github.io"  # User-level GitHub Pages URL without trailing slash
baseurl: "/top-lane-analysis"     # Repository name for baseurl

# Author information
author:
  name: "Ryan Lee"
  email: "ryanparkerlee2128@gmail.com"

# Theme settings (GitHub Pages themes, e.g., Minima)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Plugins (if needed for Jekyll/GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processing options
markdown: kramdown
highlighter: rouge

# Additional configurations for Jekyll
exclude:
  - "Gemfile"
  - "Gemfile.lock"

# Build settings for GitHub Pages
# Remove remote_theme if using theme in the config
# remote_theme: "pages-themes/minimal@v0.2.0"