remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Top Lane Factors to Win Analysis"
description: "An analysis of the critical factors for success in the top lane role of League of Legends esports."
